onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
  - "@clerk/shared"
  - "@parcel/watcher"
  - "@swc/core"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
