import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import { Manrope, IBM_Plex_Sans_Arabic, Vazirmatn, Playfair_Display, JetBrains_Mono } from "next/font/google";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { ClerkProvider } from "@clerk/nextjs";
import { notFound } from "next/navigation";
import "../globals.css";
import { localeDirection, locales, type Locale } from "@/lib/i18n/config";
import { ServiceWorkerRegistration } from "@/components/ui/ServiceWorkerRegistration";
import { SplashScreen } from "@/components/ui/SplashScreen";

const latin = Manrope({
  variable: "--font-latin",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

const arabic = IBM_Plex_Sans_Arabic({
  variable: "--font-arabic",
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const persian = Vazirmatn({
  variable: "--font-persian",
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Display serif for the "shop" / "verified" accent words. Italic only.
const display = Playfair_Display({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400"],
  style: ["italic"],
  display: "swap",
});

// Monospace for eyebrows, numbers, micro-copy per the design system.
const mono = JetBrains_Mono({
  variable: "--font-mono-display",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vesture",
  description: "Curated fashion from independent boutiques",
  // PWA — manifest is generated by app/manifest.ts. iOS-specific
  // meta tags below tell Safari to treat the app as fullscreen
  // when added to the home screen + use a translucent status bar
  // tinted by the theme color.
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Vesture",
  },
  // Mask icon for Safari pinned-tab + theme.
  other: {
    "mobile-web-app-capable": "yes",
  },
};

// `viewport` is split out of `metadata` per Next 13.4+ conventions.
// `themeColor` is the chrome / status-bar color when installed; ink
// matches the floating-nav and dark cards. `viewportFit: cover`
// lets the app paint into iOS notches / home-indicator areas, and
// `userScalable` is left on (default) so accessibility zoom works.
export const viewport: Viewport = {
  themeColor: "#212739",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(locales, locale)) notFound();

  setRequestLocale(locale);
  const dir = localeDirection[locale as Locale];

  return (
    <ClerkProvider>
      <html
        lang={locale}
        dir={dir}
        className={`${latin.variable} ${arabic.variable} ${persian.variable} ${display.variable} ${mono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col overflow-x-clip bg-mist text-ink">
          <SplashScreen />
          <ServiceWorkerRegistration />
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
